apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../default
images:
- name: cguaicadmin/notebook-controller
  newName: cguaicadmin/notebook-controller
  newTag: 20250316_1
