apiVersion: v1
kind: Namespace
metadata:
  name: ldap

---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: docker.io/twentyfouritaiwan/ldap_backend:v0.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: /code/db
              name: sqlite-data
      #terminationMessagePath: /dev/termination-log
      #terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: backend-service-account
      terminationGracePeriodSeconds: 30
      volumes:
        - name: sqlite-data
          persistentVolumeClaim:
            claimName: pvc-backend-sqlite

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-backend-sqlite
  namespace: ldap
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: ldap
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      nodePort: 31190
      targetPort: 8000

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-service-account
  namespace: ldap
