apiVersion: v1
kind: ServiceAccount
metadata:
  name: groupshare-controller
  namespace: kubeflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: groupshare-controller-clusterrole
rules:
  - apiGroups: ["kubeflow.org"]
    resources: ["profiles"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["kubeflow.org"]
    resources: ["poddefaults"]
    verbs: ["get", "create", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: groupshare-controller-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: groupshare-controller
    namespace: kubeflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: groupshare-controller-clusterrole
