apiVersion: v1
kind: Service
metadata:
  name: groupshare-webhook
  namespace: kubeflow
spec:
  selector:
    app: groupshare-validating-webhook
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8443
